# Generated by Django 4.1.6 on 2023-02-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scorecard', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'Complete'), (3, 'Reviewed'), (1, 'Draft')])),
                ('scored_on', models.DateField(blank=True, null=True)),
                ('scored_by', models.CharField(blank=True, max_length=50)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=50)),
                ('score', models.FloatField(editable=False, null=True)),
                ('comment', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='entity.entity')),
                ('scorecard_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scorecard.scorecardversion')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Yet Started'), (2, 'In Progress'), (3, 'Completed')])),
                ('min_expense', models.FloatField(default=0.0)),
                ('max_expense', models.FloatField(default=0.0)),
                ('min_effort', models.FloatField(default=0.0)),
                ('max_effort', models.FloatField(default=0.0)),
                ('units', models.IntegerField(choices=[(1, 'hours'), (2, 'days'), (3, 'weeks'), (4, 'months')], default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('mandatory', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('score', models.FloatField(editable=False, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_item_responses', to='response.response')),
                ('score_item_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_item_responses', to='scorecard.scoringitemversion')),
                ('score_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_item_responses', to='scorecard.scorelevel')),
                ('tasks', models.ManyToManyField(related_name='scoring_item_responses', to='response.task')),
            ],
        ),
    ]
