# Generated by Django 4.1.5 on 2023-01-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this entity.', max_length=250)),
                ('description', models.TextField(help_text='A description of the entity.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A type of entity for which a Scorecard will becreated, such as Application.', max_length=50, unique=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Scorecard, typically named for theAsset Type with which it is associated.', max_length=100, unique=True)),
                ('desciption', models.TextField(max_length=1000)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.entity')),
                ('scorecard_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.scorecardversion')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.entitytype'),
        ),
    ]
