# Generated by Django 4.1.5 on 2023-01-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desciption', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorch.scorecard')),
            ],
        ),
    ]
