# Generated by Django 4.1.6 on 2023-02-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Scorecard, typically named for theAsset Type with which it is associated.', max_length=100, unique=True)),
                ('desciption', models.TextField(blank=True)),
                ('max_score', models.FloatField(default=100.0, help_text='The maximum score allowed for any item.')),
                ('score_level_label', models.CharField(default='Conformance', max_length=50)),
                ('default_weight', models.FloatField(default=100.0, help_text='The default weight appliedto all ScoreItems if they do not have an override or formula.')),
                ('default_mandatory', models.BooleanField(default=False)),
                ('scorer_type', models.IntegerField(choices=[(1, 'Weighted Deduction Scorer')], default=1)),
                ('score_level_computer_type', models.IntegerField(choices=[(1, 'Threshhold Score Level Computer')], default=1)),
                ('weight_computer_type', models.IntegerField(choices=[(1, 'Expression Weight Computer')], default=1)),
                ('mandatory_computer_type', models.IntegerField(choices=[(1, 'Expression Mandatory Computer')], default=1)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='entity.entitytype')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_expr', models.TextField(blank=True, null=True)),
                ('mandatory_expr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scorecard.scoringitemversion')),
                ('scorecard_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_item_versions', to='scorecard.scorecardversion')),
                ('scoring_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scorecard.scoringitem')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItemLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(help_text='The order of the ScoringItemLevel among its peers within the Scorecard.')),
                ('help_base_url', models.URLField(help_text='The base URL for autogeneratedlinks to further help ScoreItems at this level')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_item_levels', to='scorecard.scorecard')),
            ],
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_items', to='scorecard.scoringitemlevel'),
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_items', to='scorecard.scorecard'),
        ),
        migrations.CreateModel(
            name='ScoreLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order of this ScoreLevel among its peers within the scorecard.')),
                ('name', models.CharField(max_length=20)),
                ('score', models.FloatField(help_text='The score assigned by thislevel when directly chosen, must be <= the Scorecard max score.')),
                ('threshold', models.FloatField(help_text='The lower value at which this level is displayed for computed scores. Must be less than score to be useful.')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_levels', to='scorecard.scorecard')),
            ],
        ),
    ]
